import type { Poem, Author, ForumTopic, Statistics } from "./types";

export const MOCK_POEMS: Poem[] = [
  {
    id: 1,
    title: "Đoạn trường tân thanh (Truyện Kiều)",
    slug: "doan-truong-tan-thanh",
    author: { id: 1, name: "Nguyễn Du", slug: "nguyen-du" },
    category: { id: 1, name: "Truyện thơ Nôm", slug: "truyen-tho-nom" },
    view_count: 142850,
    is_member_poem: false,
    like_count: 0,
    excerpt:
      "Trăm năm trong cõi người ta,\nChữ tài chữ mệnh khéo là ghét nhau.\nTrải qua một cuộc bể dâu,\nNhững điều trông thấy mà đau đớn lòng.",
  },
  {
    id: 2,
    title: "Cáo bình Ngô",
    slug: "cao-binh-ngo",
    author: { id: 2, name: "Nguyễn Trãi", slug: "nguyen-trai" },
    category: { id: 2, name: "Cáo văn", slug: "cao-van" },
    view_count: 98420,
    is_member_poem: false,
    like_count: 0,
    excerpt:
      "Việc nhân nghĩa cốt ở yên dân,\nQuân điếu phạt trước lo trừ bạo.",
  },
  {
    id: 3,
    title: "Tĩnh dạ tư",
    slug: "tinh-da-tu",
    author: { id: 3, name: "Lý Bạch", slug: "ly-bach" },
    category: { id: 3, name: "Đường thi", slug: "duong-thi" },
    view_count: 87500,
    is_member_poem: false,
    like_count: 0,
    excerpt: "床前明月光，\n疑是地上霜。\n舉頭望明月，\n低頭思故鄉。",
  },
  {
    id: 4,
    title: "Qua đèo Ngang",
    slug: "qua-deo-ngang",
    author: { id: 4, name: "Bà Huyện Thanh Quan", slug: "ba-huyen-thanh-quan" },
    category: { id: 4, name: "Thơ Đường luật", slug: "duong-luat" },
    view_count: 74200,
    is_member_poem: false,
    like_count: 0,
    excerpt:
      "Bước tới đèo Ngang, bóng xế tà,\nCỏ cây chen đá, lá chen hoa.\nLom khom dưới núi, tiều vài chú,\nLác đác bên sông, rợ mấy nhà.",
  },
  {
    id: 5,
    title: "Thương vợ",
    slug: "thuong-vo",
    author: { id: 5, name: "Trần Tế Xương", slug: "tran-te-xuong" },
    category: { id: 4, name: "Thơ Đường luật", slug: "duong-luat" },
    view_count: 65100,
    is_member_poem: false,
    like_count: 0,
    excerpt:
      "Quanh năm buôn bán ở mom sông,\nNuôi đủ năm con với một chồng.",
  },
  {
    id: 6,
    title: "Đây thôn Vĩ Dạ",
    slug: "day-thon-vi-da",
    author: { id: 6, name: "Hàn Mặc Tử", slug: "han-mac-tu" },
    category: { id: 5, name: "Thơ mới", slug: "tho-moi" },
    view_count: 59800,
    is_member_poem: false,
    like_count: 0,
    excerpt:
      "Sao anh không về chơi thôn Vĩ?\nNhìn nắng hàng cau nắng mới lên.",
  },
  {
    id: 7,
    title: "Tống biệt hành",
    slug: "tong-biet-hanh",
    author: { id: 7, name: "Thâm Tâm", slug: "tham-tam" },
    category: { id: 5, name: "Thơ mới", slug: "tho-moi" },
    view_count: 43200,
    is_member_poem: false,
    like_count: 0,
    excerpt:
      "Đưa người ta không đưa qua sông,\nSao có tiếng sóng ở trong lòng?",
  },
  {
    id: 8,
    title: "Mùa thu vàng",
    slug: "mua-thu-vang",
    author: { id: 20, name: "Hoàng Lan Hương", slug: "hoang-lan-huong" },
    category: { id: 6, name: "Thơ thành viên", slug: "tho-thanh-vien" },
    view_count: 1240,
    is_member_poem: true,
    like_count: 0,
    excerpt:
      "Lá vàng rơi nhẹ cuối thu,\nGió mang hơi lạnh vào trong giấc mơ.",
  },
];

export const MOCK_AUTHORS: Author[] = [
  {
    id: 1,
    name: "Nguyễn Du",
    slug: "nguyen-du",
    birth_year: "1766",
    death_year: "1820",
    country: "Việt Nam",
    era: "Trung đại — Hậu Lê / Nguyễn",
    poem_count: 320,
    is_verified: true,
    biography:
      "Nguyễn Du (阮攸, 1766–1820) là đại thi hào của dân tộc Việt Nam, tác giả của Truyện Kiều — kiệt tác thơ Nôm bất hủ. Ông sinh tại làng Tiên Điền, huyện Nghi Xuân, Hà Tĩnh trong một dòng họ khoa bảng nổi tiếng.",
  },
  {
    id: 2,
    name: "Nguyễn Trãi",
    slug: "nguyen-trai",
    birth_year: "1380",
    death_year: "1442",
    country: "Việt Nam",
    era: "Trung đại — Trần / Hồ / Lê sơ",
    poem_count: 254,
    is_verified: true,
    biography:
      "Nguyễn Trãi (阮廌, 1380–1442) là nhà thơ, nhà văn, nhà chính trị lỗi lạc thời Lê sơ. Tác giả của Bình Ngô đại cáo — áng hùng văn thiên cổ.",
  },
  {
    id: 3,
    name: "Lý Bạch",
    slug: "ly-bach",
    birth_year: "701",
    death_year: "762",
    country: "Trung Quốc",
    era: "Đường — Thịnh Đường",
    poem_count: 1100,
    is_verified: true,
  },
  {
    id: 4,
    name: "Bà Huyện Thanh Quan",
    slug: "ba-huyen-thanh-quan",
    country: "Việt Nam",
    era: "Trung đại — Nguyễn",
    poem_count: 6,
    is_verified: true,
  },
  {
    id: 5,
    name: "Trần Tế Xương",
    slug: "tran-te-xuong",
    birth_year: "1870",
    death_year: "1907",
    country: "Việt Nam",
    era: "Trung đại — Nguyễn (cuối)",
    poem_count: 150,
    is_verified: true,
  },
  {
    id: 6,
    name: "Hàn Mặc Tử",
    slug: "han-mac-tu",
    birth_year: "1912",
    death_year: "1940",
    country: "Việt Nam",
    era: "Thơ mới (1932–1945)",
    poem_count: 180,
    is_verified: true,
  },
];

export const MOCK_STATS: Statistics = {
  total_poems: 112381,
  total_authors: 5284,
  total_countries: 111,
  total_members: 48200,
  total_translations: 23500,
};

export const MOCK_FORUM_TOPICS: ForumTopic[] = [
  {
    id: 1,
    title: 'Phân tích nghệ thuật "Truyện Kiều" qua lăng kính văn học hiện đại',
    slug: "phan-tich-nghe-thuat-truyen-kieu",
    category: "Phân tích văn học",
    author_name: "GS. Nguyễn Văn A",
    reply_count: 42,
    view_count: 3280,
    last_reply_at: "2026-05-29T14:22:00Z",
    created_at: "2026-05-20T08:00:00Z",
    pinned: true,
  },
  {
    id: 2,
    title: "Luật bằng-trắc trong thơ Đường luật thất ngôn bát cú",
    slug: "luat-bang-trac-duong-luat",
    category: "Luật thơ",
    author_name: "ThS. Trần Thị B",
    reply_count: 18,
    view_count: 1540,
    last_reply_at: "2026-05-28T10:15:00Z",
    created_at: "2026-05-22T09:30:00Z",
  },
  {
    id: 3,
    title: "Hỏi về cách dịch câu chữ Hán trong bài Tống biệt hành",
    slug: "hoi-dich-chu-han-tong-biet-hanh",
    category: "Dịch thuật",
    author_name: "Độc giả Lê C",
    reply_count: 7,
    view_count: 620,
    last_reply_at: "2026-05-27T16:45:00Z",
    created_at: "2026-05-25T11:00:00Z",
  },
];
